### ISSUE TITLE
Full file + segmented files

### ISSUE THREAD

**Issue by maltfield** [MirzaAreebBaig/Woocommerce-US-ZipCodes-TaxRates#1]
First, thank you so much for preparing this csv file. I spent a long time looking for one csv for all the US tax rates.

Unfortunately, I found that my site gives 417 and 504 errors when trying to process this >1M CSV file containing >39,000 entries.

While I don't want you to stop providing a single combined .zip file, I wonder if it's possible that you could create a CI pipeline that automatically splits it out into files of a more manageable size? Perhaps one set that's 50x files (one for each state)?

And maybe also 5x files, one for each of:
1. South-West Continental
2. South-East Continental
3. Northwest Continental
4. Northeast Continental
5. Non-continental

**Comment by maltfield** [comment]
Temp workaround: you can split the files into 1,000 records each as follows

```
git clone https://github.com/MirzaAreebBaig/Woocommerce-US-ZipCodes-TaxRates.git
cd Woocommerce-US-ZipCodes-TaxRates
split -l 1000 tax_rates.csv --additional-suffix .csv tax_rates-
files=`ls -1 | grep -i tax_rates- | grep -vi tax_rates-aa.csv`
for f in $files; do echo $f; sed -i "1i`head -n1 tax_rates.csv`" $f; done
```

**Comment by MirzaAreebBaig** [comment]
Hey,
Can we do it state wise what are your thoughts on this?

**Comment by maltfield** [comment]
One file for each state sounds great

**Comment by MirzaAreebBaig** [comment]
Hey, @maltfield 
All state wise tax files has been uploaded please check it here 
https://github.com/MirzaAreebBaig/Woocommerce-US-ZipCodes-TaxRates/tree/main/Statewise%20tax
